"""remove image to menu

Revision ID: 74432f124e4a
Revises: 5d9639d62178
Create Date: 2024-05-10 18:26:25.115808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74432f124e4a'
down_revision = '5d9639d62178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', mysql.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
