"""add address

Revision ID: 9f16da8b34c3
Revises: 630340dc0601
Create Date: 2024-04-30 16:52:50.962353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f16da8b34c3'
down_revision = '630340dc0601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_number', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=10), nullable=True))

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=2147483648),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.LargeBinary(length=2147483648),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('postcode')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('street')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('street_number')

    # ### end Alembic commands ###
