"""add instructions field

Revision ID: dfd203caf079
Revises: 2351a4a1f398
Create Date: 2024-05-08 18:40:12.507833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd203caf079'
down_revision = '2351a4a1f398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
